### GET request to example server
GET http://localhost:8080
###
GET http://localhost:8080/api/v1/feedback
###
POST http://localhost:8080/api/v1/feedback
Content-Type: application/json

{
  "player_name": "Emin",
  "player_last_name": "Dari",
  "player_email": "dariemin@gmail.com",
  "message": "Work on your scanning",
  "rating": 7.6
}